apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: fiap-mba-app
spec:
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    name: fiap-mba-app
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 75
          type: Utilization
