kind: Service
apiVersion: v1
metadata:
  name: fiap-mba-app
  namespace: wmirandamba-dev
  uid: 46d3a5fd-68b4-492c-b895-e3f316564454
  resourceVersion: '537619543'
  creationTimestamp: '2022-01-13T23:30:33Z'
  labels:
    app: fiap-mba-app
    app.kubernetes.io/component: fiap-mba-app
    app.kubernetes.io/instance: fiap-mba-app
    app.kubernetes.io/name: fiap-mba-app
    app.kubernetes.io/part-of: fiap-mba-app
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2022-01-13T23:30:33Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
        'f:spec':
          'f:internalTrafficPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":3000,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector': {}
          'f:sessionAffinity': {}
          'f:type': {}
spec:
  clusterIP: 172.30.71.60
  ipFamilies:
    - IPv4
  ports:
    - name: 3000-tcp
      protocol: TCP
      port: 3000
      targetPort: 3000
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.71.60
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: fiap-mba-app
    deploymentconfig: fiap-mba-app
status:
  loadBalancer: {}
