kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"creationTimestamp":"2022-01-12T00:07:24Z","finalizers":["kubernetes.io/pvc-protection"],"labels":{"template":"mongodb-persistent-template","template.openshift.io/template-instance-owner":"55871031-0a0d-4179-8afe-3e777353b10f"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:template":{},"f:template.openshift.io/template-instance-owner":{}}},"f:spec":{"f:accessModes":{},"f:resources":{"f:requests":{".":{},"f:storage":{}}},"f:volumeMode":{}}},"manager":"openshift-controller-manager","operation":"Update","time":"2022-01-12T00:07:24Z"}],"name":"fiap-mba-db","namespace":"wmirandamba-dev","resourceVersion":"530148791","uid":"b223ef0c-ae1d-411f-9494-8f11dfc0fb7a"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"gp2","volumeMode":"Filesystem"},"status":{"phase":"Pending"}}
  resourceVersion: '537709872'
  name: fiap-mba-db
  uid: f994b271-c294-4313-b5f5-b58d78eb4013
  creationTimestamp: '2022-01-13T00:07:07Z'
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: v1
      time: '2022-01-13T00:07:07Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:finalizers':
            .: {}
            'v:"kubernetes.io/pvc-protection"': {}
          'f:labels':
            .: {}
            'f:template': {}
            'f:template.openshift.io/template-instance-owner': {}
        'f:spec':
          'f:accessModes': {}
          'f:resources':
            'f:requests':
              .: {}
              'f:storage': {}
          'f:storageClassName': {}
          'f:volumeMode': {}
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2022-01-14T00:05:26Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            'f:app': {}
  namespace: wmirandamba-dev
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: fiap-mba-db
    template: mongodb-persistent-template
    template.openshift.io/template-instance-owner: 55871031-0a0d-4179-8afe-3e777353b10f
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
status:
  phase: Pending
