name: Deploy Application

on:
  # push:
  #   branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    env:
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_SERVER_URL: ${{ secrets.OPENSHIFT_SERVER_URL }}
      DATABASE_ADMIN_PASSWORD: ${{ secrets.DATABASE_ADMIN_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: OpenShift - Install
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6' 
          
      - name: OpenShift - Login
        run: oc login --token=$OPENSHIFT_TOKEN --server=$OPENSHIFT_SERVER_URL
        
      - name: OpenShift - Select project
        run: oc project wmirandamba-dev

      - name: create database secrets
        run:  oc new-build --name myapp --context-dir app 