name: Deploy Resources

on:
  workflow_dispatch:

jobs:
  deploy:
    env:
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_SERVER_URL: ${{ secrets.OPENSHIFT_SERVER_URL }}
      DATABASE_ADMIN_PASSWORD: ${{ secrets.DATABASE_ADMIN_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: OpenShift - Install
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6' 
          
      - name: OpenShift - Login
        run: oc login --token=$OPENSHIFT_TOKEN --server=$OPENSHIFT_SERVER_URL
        
      - name: OpenShift - Select project
        run: oc project wmirandamba-dev

      - name: create database secrets
        run: |
          oc create secret generic fiap-mba-db \
            --from-literal=database-admin-password=$DATABASE_ADMIN_PASSWORD \
            --from-literal=database-name=$DATABASE_NAME \
            --from-literal=database-password=$DATABASE_PASSWORD \
            --from-literal=database-user=$DATABASE_USER

      - name: deploy database
        run: oc apply -k resources/database

      - name: deploy image-stream and latest tag
        run: oc apply -f resources/image-stream/image-stream.yaml

      - name: install app dependencies
        run: cd app && npm i && cd ..

      - name: build app
        run: docker build -t default-route-openshift-image-registry.apps.sandbox-m2.ll9k.p1.openshiftapps.com/wmirandamba-dev/fiap-mba-app:latest app/

      - name: push app image
        run: |
          docker login -u `oc whoami` -p `oc whoami --show-token` default-route-openshift-image-registry.apps.sandbox-m2.ll9k.p1.openshiftapps.com && \
          docker push default-route-openshift-image-registry.apps.sandbox-m2.ll9k.p1.openshiftapps.com/wmirandamba-dev/fiap-mba-app

      - name: deploy application
        run: oc apply -k resources/application

      
